#ifndef SHADERTASTIC_PARAMETER_GROUP_CONDITION_HPP
#define SHADERTASTIC_PARAMETER_GROUP_CONDITION_HPP

enum effect_parameter_group_condition {
    PARAM_GROUP_CONDITION_EQUAL,
    PARAM_GROUP_CONDITION_NOT_EQUAL,
    PARAM_GROUP_CONDITION_GREATER,
    PARAM_GROUP_CONDITION_GREATER_OR_EQUAL,
    PARAM_GROUP_CONDITION_LESS,
    PARAM_GROUP_CONDITION_LESS_OR_EQUAL,
};

#endif // SHADERTASTIC_PARAMETER_GROUP_CONDITION_HPP
