#ifndef SHADERTASTIC_PARAMETER_GROUP_IF_HPP
#define SHADERTASTIC_PARAMETER_GROUP_IF_HPP

enum effect_parameter_group_if {
    PARAM_GROUP_IF_BOOL,
    PARAM_GROUP_IF_INT,
    PARAM_GROUP_IF_FLOAT,
    
    PARAM_GROUP_IF_UNKNOWN,
};

#endif // SHADERTASTIC_PARAMETER_GROUP_IF_HPP
